import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const popins = Poppins({
  weight: "600",
  variable: "--font-popins",
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${popins.variable}`}>
      <header>
        <h1>Davis Family Challenge</h1>
        <nav>
          <ul>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/leaderboard">Leaderboard</Link></li>
            <li><Link href="/challenges">Yearly Challenges</Link></li>
            <li><Link href="/about">About Us</Link></li>
          </ul>
        </nav>
      </header>
        {children}
        <footer>
        <p>&copy; 2024 Davis Family Challenge. All rights reserved.</p>
      </footer>
      </body>
    </html>
  );
}
